import Head from 'next/head'
import { Inter } from 'next/font/google'
import Home from './home'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
  }, [])
  return isClient ? (
    <>
      <Head>
        <title>Rekha Kumari - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  ) : null
}
